export const ActionType = {
  COME_BACK_TO_STARTPAGE: 'COME_BACK_TO_STARTPAGE',
  FETCH_TEST_START: 'FETCH_TEST_START',
  FETCH_TEST_SUCCESS: 'FETCH_TEST_SUCCESS',
  FETCH_TEST_ERROR: 'FETCH_TEST_ERROR',
  TIME_START: 'TIME_START',
};
export const llll = () => null;
